### ISSUE TITLE
How to prevent errors "Connection reset by peer" at docker container

### ISSUE THREAD

**Issue by shogogg** [betalo-sweden/await#27]
Hi,

When I use await for http resource, an error occurred at docker container below:

> ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:13

Could you tell me how to prevent it?

**Comment by djui** [comment]
Hi! Could you provide me with the full example/cli you used?

**Comment by djui** [comment]
On a not-available resource I get:

```
$ ./await -vv -t 3s http://1233243244324324324.com -- echo OK
2016/11/30 21:33:13 Awaiting resource: http://1233243244324324324.com
2016/11/30 21:33:13 Resource unavailable: Get http://1233243244324324324.com: dial tcp: lookup 1233243244324324324.com: no such host
2016/11/30 21:33:13 Resource unavailable: Get http://1233243244324324324.com: dial tcp: lookup 1233243244324324324.com: no such host
2016/11/30 21:33:14 Resource unavailable: Get http://1233243244324324324.com: dial tcp: lookup 1233243244324324324.com: no such host
2016/11/30 21:33:14 Resource unavailable: Get http://1233243244324324324.com: dial tcp: lookup 1233243244324324324.com: no such host
2016/11/30 21:33:15 Resource unavailable: Get http://1233243244324324324.com: dial tcp: lookup 1233243244324324324.com: no such host
2016/11/30 21:33:15 Resource unavailable: Get http://1233243244324324324.com: dial tcp: lookup 1233243244324324324.com: no such host
2016/11/30 21:33:16 Resource unavailable: Get http://1233243244324324324.com: dial tcp: lookup 1233243244324324324.com: no such host
2016/11/30 21:33:16 Timeout exceeded
```

And on an available resource I get:

```
$ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 ...
```

```
$ ./await -vv -t 3s http://localhost:8000 -- echo OK
2016/11/30 21:34:30 Awaiting resource: http://localhost:8000
2016/11/30 21:34:30 All resources available
2016/11/30 21:34:30 Runnning command: [echo OK]
OK
```

```
127.0.0.1 - - [30/Nov/2016 21:34:30] "GET / HTTP/1.1" 200 -
```

I assume you mean the error message is on the HTTP server side. Which server is that?

**Comment by shogogg** [comment]
Command is `await -t 5m http://localhost:10080/ -- true`, and I use WEBrick.

**Comment by djui** [comment]
I tried to reproduce this scenario but don't see the same symptoms:

```
$ ./await -vv -t 3s http://localhost:8000 -- echo OK
2016/12/01 12:10:48 Awaiting resource: http://localhost:8000
2016/12/01 12:10:48 All resources available
2016/12/01 12:10:48 Runnning command: [echo OK]
OK
```

```
$ ruby web.rb
[2016-12-01 12:10:47] INFO  WEBrick 1.3.1
[2016-12-01 12:10:47] INFO  ruby 2.3.1 (2016-04-26) [x86_64-darwin16]
[2016-12-01 12:10:47] DEBUG MyServlet is mounted on /.
[2016-12-01 12:10:47] INFO  WEBrick::HTTPServer#start: pid=72388 port=8000
[2016-12-01 12:10:48] DEBUG accept: ::1:59016
[2016-12-01 12:10:48] DEBUG MyServlet is invoked.
::1 - - [01/Dec/2016:12:10:48 CET] "GET /web.rb HTTP/1.1" 200 42
- -> /web.rb
[2016-12-01 12:10:48] DEBUG close: ::1:59016
```

```rb
# web.rb
require 'webrick'

class MyServlet < WEBrick::HTTPServlet::AbstractServlet
  def do_GET (request, response)
    response.status = 200
    response.header['Connection'] = 'keep-alive'
    response.content_type = "text/plain"
    response.body = "hello world"
  end
end

log = WEBrick::Log.new nil, WEBrick::BasicLog::DEBUG
server = WEBrick::HTTPServer.new :Port => 8000, :Logger => log
server.mount "/", MyServlet
trap('INT') { server.stop }
server.start
```

- Do you see the error message on the Webrick side?
- Does it happen for each availability test check?
- What is your webrick version?
- Which log level do you use?

**Comment by shogogg** [comment]
@djui Thanks for your kind cooperation.

I'm sorry that I don't know much about ruby, rails and webrick.

I'm using Redmine 3.3.1 in my docker container with command `bundle exec rails server -b 0.0.0.0`. I don't know log level, webrick version.

The error occurred at Redmine container every time when I run `await -t 5m http://localhost:3000/`.

All error message is below:

```
[2016-12-01 21:00:20] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:9
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:82:in `eof?'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:82:in `run'
        /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by djui** [comment]
I think I am out of ideas. I used a Redmine docker image and got this:

```
$ ./await-darwin-amd64 -vv -t 30s http://localhost:10083 -- echo OK
2016/12/02 19:26:30 Awaiting resource: http://localhost:10083
2016/12/02 19:26:30 Resource unavailable: Get http://localhost:10083: dial tcp [::1]:10083: getsockopt: connection refused
2016/12/02 19:26:30 Resource unavailable: Get http://localhost:10083: dial tcp [::1]:10083: getsockopt: connection refused
2016/12/02 19:26:31 Resource unavailable: Get http://localhost:10083: dial tcp [::1]:10083: getsockopt: connection refused
2016/12/02 19:26:31 Resource unavailable: Get http://localhost:10083: dial tcp [::1]:10083: getsockopt: connection refused
2016/12/02 19:26:33 Resource unavailable: Get http://localhost:10083: EOF
2016/12/02 19:26:33 Resource unavailable: Get http://localhost:10083: EOF
2016/12/02 19:26:34 Resource unavailable: Get http://localhost:10083: EOF
2016/12/02 19:26:34 Resource unavailable: 502 Bad Gateway
2016/12/02 19:26:35 Resource unavailable: 502 Bad Gateway
2016/12/02 19:26:35 Resource unavailable: 502 Bad Gateway
2016/12/02 19:26:36 Resource unavailable: 502 Bad Gateway
2016/12/02 19:26:36 Resource unavailable: 502 Bad Gateway
2016/12/02 19:26:37 Resource unavailable: 502 Bad Gateway
2016/12/02 19:26:38 All resources available
2016/12/02 19:26:38 Runnning command: [echo OK]
OK
```

```
$ docker run --name=redmine --rm -it --link=postgresql-redmine:postgresql --publish=10083:80 --env='REDMINE_PORT=10083' --volume=redmine:/home/redmine/data sameersbn/redmine:3.3.1
Initializing logdir...
Initializing datadir...
Symlinking dotfiles...
Installing configuration templates...
Configuring redmine...
Configuring redmine::database
Configuring redmine::unicorn...
Configuring redmine::secret_token...
Generating a session token...
Note:
  All old sessions will become invalid.
  Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
  **SHOULD** be defined if you have a load-balancing Redmine cluster.
Configuring redmine::max_concurrent_ajax_uploads...
Configuring redmine::sudo_mode...
Configuring redmine::autologin_cookie...
Configuring redmine::backups...
Configuring nginx...
Configuring nginx::redmine...
Installing plugins...
Installing themes...
2016-12-02 16:00:57,946 CRIT Supervisor running as root (no user in config file)
2016-12-02 16:00:57,946 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2016-12-02 16:00:57,947 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
2016-12-02 16:00:57,947 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2016-12-02 16:00:57,969 INFO RPC interface 'supervisor' initialized
2016-12-02 16:00:57,970 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-12-02 16:00:57,970 INFO supervisord started with pid 1
2016-12-02 16:00:58,975 INFO spawned: 'unicorn' with pid 223
2016-12-02 16:00:58,978 INFO spawned: 'cron' with pid 224
2016-12-02 16:00:58,982 INFO spawned: 'nginx' with pid 225
2016-12-02 16:01:00,426 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-02 16:01:00,426 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-12-02 16:01:00,427 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

So no special error output there.

Is your Redmine docker image publicly available? That would bring as close as possible to an idea of what is going on.

**Comment by shogogg** [comment]
@djui Sorry for my late reply.

I'm using private docker image, but similar to [official it](https://hub.docker.com/_/redmine/).

I think, sameersbn/redmine not correspond with this case, because it is using nginx.

- [Dockerfile of redmine](https://github.com/docker-library/redmine/blob/master/3.3/Dockerfile)
- [Dockerfile of sameersbn/redmine](https://github.com/sameersbn/docker-redmine/blob/master/Dockerfile)
